#Configuration for CI build at https://travis-ci.org/mapstruct/mapstruct-idea

language: java

jdk:
  - oraclejdk8

env:
  - IDEA_VERSION=LATEST-EAP-SNAPSHOT
  - IDEA_VERSION=2018.2.4

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

# Don't let Travis CI execute './gradlew assemble' by default
install:
# Display Gradle, Groovy, JVM and other versions
  - ./gradlew -version

script:
  - ./gradlew build

after_success:
  - ./gradlew jacocoTestReport && bash <(curl -s https://codecov.io/bash)
