name: CI

on: [push, pull_request]

jobs:
  test_idea:
    strategy:
      fail-fast: false
      matrix:
        version:
          - { jdk: 21, idea: 2025.1 }
          - { jdk: 21, idea: 2025.2 }
          - { jdk: 21, idea: 2025.3 }
          - { jdk: 21, idea: 2026.1 }
          - { jdk: 21, idea: LATEST-EAP-SNAPSHOT }
    name: 'IDEA ${{ matrix.version.idea }}'
    env:
      IDEA_VERSION: ${{ matrix.version.idea }}
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - name: 'Set up JDK'
        uses: actions/setup-java@1bcf9fb12cf4aa7d266a90ae39939e61372fe520 # v5.4.0
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.version.jdk }}
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@3f131e8634966bd73d06cc69884922b02e6faf92 # v6.2.0
      - name: 'Test'
        run: ./gradlew --warning-mode=all build
      - name: 'Generate coverage report'
        run: ./gradlew --warning-mode=all jacocoTestReport
      - name: 'Upload coverage to Codecov'
        if: github.repository == 'mapstruct/mapstruct-idea' &&  matrix.version.idea  == '2025.1'
        uses: codecov/codecov-action@fb8b3582c8e4def4969c97caa2f19720cb33a72f # v7.0.0
        with:
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
